### ISSUE TITLE
Improve commenting

### ISSUE THREAD

**Issue by gregkrsak** [kotcity/kotcity#17]
https://github.com/kotcity/kotcity/blob/8dad3e23693372dffc5380866b9954969dc1a46d/src/main/kotlin/kotcity/pathfinding/Pathfinder.kt#L63

**Comment by kotcity** [comment]
How would you like it improved?

**Comment by gregkrsak** [comment]
In general, comments should use professional language and refrain from being emotional outbursts.


In this specific case, you could replace the noted comment with a clear statement describing your displeasure or surprise, and perhaps add potential solutions.

**Comment by sabieber** [comment]
Or .... we could just have a little fun in this serious world ;)

**Comment by gregkrsak** [comment]
A generic defense for crude, immature behavior but it is indeed an option! I think you guys are better than this, but it's your show.

**Comment by sabieber** [comment]
I was just kidding and will leave @kotcity deciding how to procede with code comments

**Comment by gregkrsak** [comment]
:+1:

**Comment by kotcity** [comment]
@gregkrsak Thanks for your suggestion for our project. I've closed this with PR #18 

In your travels through the source, let us know if you have any ideas / questions. We welcome all input.
