### ISSUE TITLE
Move Repo to a Organization

### ISSUE THREAD

**Issue by chfzdn** [kotcity/kotcity#6]
Hello,

As part of decentralization, I will propose that the repository will be moved into @kotcity organization account. Yes, it's called **kotcity**. The repo currently sits on a personal account technically, this is proved by personalized profile info rather than streamlined profile view. Also, organization account benefits from more granular permissions, which will be needed in the future. It isn't nice to hide with personal account in the open source world or version control in general.

Sorry if I have mistakes. Thanks.

**Comment by kotcity** [comment]
I will consider this -- I have not run an org before. So far I am managing the contributions no problem.
