### ISSUE TITLE
Document the game (aka PDF manual)

### ISSUE THREAD

**Issue by WPFilmmaker** [kotcity/kotcity#66]
It would be nice to have a manual of the game in PDF, possibly shipped with the game as well with the option to launch it from th game itself.

Since at the moment (from what I understood) the game is a 1 person project I invite everyone who can to contribute to said manual and to add a "+1" if you like the idea.

**Comment by sabieber** [comment]
We could start this as a wiki page or google docs document so everyone can contribute to said manual

**Comment by WPFilmmaker** [comment]
That would be a great idea! Hope to see the community growing around the game!

**Comment by sabieber** [comment]
If you want to chat a little and discuss ideas a little bit more quickly i would encourage you to check out our [Gitter Channel](https://gitter.im/kotcity/Lobby). Its really active (especially the last view days) and all kinds of people contributing to this project hang out there.

**Comment by WPFilmmaker** [comment]
Thanks I will check it out when I have some free time! :)

**Comment by kotcity** [comment]
Would love to see a manual but until we are feature-complete (or someone volunteers) I don't plan on investing any time in it (yet). If you want to contribute a manual, let's talk, but I won't worry about it in the meantime.
