### ISSUE TITLE
"city information" broken or not yet implemented

### ISSUE THREAD

**Issue by WPFilmmaker** [kotcity/kotcity#67]
As per title, I click on it and nothing happens. I am on Lubuntu 16.04.3 openjfx 8.0.60 kotcity is 0.49.2.

**Comment by sabieber** [comment]
As #68 this is not yet implemented. A pull request or discussion about what could be displayed there is highly welcomed.

**Comment by kotcity** [comment]
Summed up perfectly by @sabieber. I love your input on the project, but we're pretty aware of these gaps in the game. Feel free to come chat with us on Gitter https://gitter.im/kotcity/Lobby

At this stage, these "incomplete" issues don't help us that much. Once we are feature complete (or nearly there) these types of reports will be essential.
