### ISSUE TITLE
"about" broken or not yet implemented

### ISSUE THREAD

**Issue by WPFilmmaker** [kotcity/kotcity#68]
As per title, I click on it and nothing happens. I am on Lubuntu 16.04.3 openjfx 8.0.60 kotcity is 0.49.2.

**Comment by sabieber** [comment]
Yeah I think this feature is not yet implemented. If you are a developer yourself you maybe could provide a basic implementation as a pull request. If not thats okay too, just have to wait a little bit till its done.

**Comment by WPFilmmaker** [comment]
@sabieber I wish I was! unfortunately I am just a FLOSS enthusiast who likes contributing back to some projects by reporting bugs and ideas. Every little helps I suppose :)

**Comment by sabieber** [comment]
Hey man thats awesome too! Absolutely it helps. At the very least this puts the missing screen on our radar and starts discussion on what should be displayed there.

**Comment by kotcity** [comment]
@WPFilmmaker If you'd like to contribute, let's talk about you amending our ROADMAP (on the wiki) vs opening issues.
