### ISSUE TITLE
Question: How to add houses and start the game?

### ISSUE THREAD

**Issue by WPFilmmaker** [kotcity/kotcity#69]
This is the most basic question...however I couldn't find a way to do so, how do you do that? I have roads,job center, power plant, all set up but no houses with no residents :(

**Comment by sabieber** [comment]
You need to mark zone near streets (houses spawn in zones a maximum of 3 blocks distanced from a road).
You also need a good balance between the thee zone types (redistential, commercial, industrial) as residential provides workers, commercial provides goods and industrial provides jobs.

So after zoning some areas next to roads you should see houses popping up after some time.

Advisers will be added to the game in the near future which could provide you with information like this (like a interactive tutorial).

**Comment by WPFilmmaker** [comment]
@sabieber Thanks a lot! i will try!

**Comment by kotcity** [comment]
Summed up perfectly by @sabieber
